### ISSUE TITLE
Unhandled exception. Azure.RequestFailedException: The value for one of the XML nodes is not in the correct format.

### ISSUE THREAD

**Issue by n3wjack** [lauchacarro/Azure-Storage-Action#7]
I'm suddenly getting this error when deploying usin the Azure storage action. It worked fine a few months ago and didn't change anything on Azure.
Any ideas what could be causing this?

Here's the stack trace I'm seeing in the failed build step:

 at Azure.Storage.Blobs.BlobRestClient.Service.SetPropertiesAsync_CreateResponse(Response response)
   at Azure.Storage.Blobs.BlobRestClient.Service.SetPropertiesAsync(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, Uri resourceUri, BlobServiceProperties blobServiceProperties, Nullable`1 timeout, String requestId, Boolean async, String operationName, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobServiceClient.SetPropertiesInternal(BlobServiceProperties properties, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobServiceClient.SetPropertiesAsync(BlobServiceProperties properties, CancellationToken cancellationToken)
   at AzureStorageAction.BlobCommands.Commands.EnabledStaticWebSiteCommand.ExecuteAction() in /home/runner/work/_actions/lauchacarro/Azure-Storage-Action/master/src/AzureStorageAction/BlobCommands/Commands/EnabledStaticWebSiteCommand.cs:line 45
   at AzureStorageAction.BlobCommands.BlobCommandManager.ExecuteCommand() in /home/runner/work/_actions/lauchacarro/Azure-Storage-Action/master/src/AzureStorageAction/BlobCommands/BlobCommandManager.cs:line 19
   at AzureStorageAction.Program.Main(String[] args) in /home/runner/work/_actions/lauchacarro/Azure-Storage-Action/master/src/AzureStorageAction/Program.cs:line 25
   at AzureStorageAction.Program.<Main>(String[] args)
Error: The process '/opt/hostedtoolcache/dncs/3.0.100/x64/dotnet' failed with exit code 134
    at ExecState._setResult (/home/runner/work/_actions/lauchacarro/Azure-Storage-Action/master/node_modules/@actions/exec/lib/toolrunner.js:561:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/lauchacarro/Azure-Storage-Action/master/node_modules/@actions/exec/lib/toolrunner.js:544:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/lauchacarro/Azure-Storage-Action/master/node_modules/@actions/exec/lib/toolrunner.js:444:27)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
Error: The process '/opt/hostedtoolcache/dncs/3.0.100/x64/dotnet' failed with exit code 134
    at ExecState._setResult (/home/runner/work/_actions/lauchacarro/Azure-Storage-Action/master/node_modules/@actions/exec/lib/toolrunner.js:561:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/lauchacarro/Azure-Storage-Action/master/node_modules/@actions/exec/lib/toolrunner.js:544:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/lauchacarro/Azure-Storage-Action/master/node_modules/@actions/exec/lib/toolrunner.js:444:27)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

**Comment by n3wjack** [comment]
This happens in the v1.1 of the action. I specified the version to v1.0 in my Yaml file, and that still works as before. So I'm good for now, but the current v1.1 seems to be broken.
